const { LinkedList } = require("./LinkedList");
const linkedList = new LinkedList();
linkedList.append(1);
linkedList.append(5);
linkedList.append(2);
linkedList.append(1444);
linkedList.append(3);
linkedList.append(39);
linkedList.append(99);
console.log("the size of linked list is: " + linkedList.size());
console.log("the head value of linked list: " + linkedList.head());
console.log("the tail value of linked list: " + linkedList.tail());
console.log("the value at 5 in the linked list: " + linkedList.at(5));
linkedList.pop();
console.log("the tail value of linked list: " + linkedList.tail());
console.log("Linked list contains 1444: " + linkedList.contains(1444));
console.log("Position of 39:" + linkedList.find(39));
console.log("Linked list to string is: " + linkedList.toString());
linkedList.insertAt(1000, 3);
console.log("Linked list to string is: " + linkedList.toString());
linkedList.removeAt(3);
console.log("Linked list to string is: " + linkedList.toString());
